version: '3'

services:
  postgres:
    build:
      context: '.'
      dockerfile: './postgres/Dockerfile'
    environment: # variaveis de ambiente
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: paginasamarelas
    ports:
      - '5432-5432' #porta do postgres
    networks: 
      - 'firstproject' #rede de ligação do docker 
    volumes:
      - 'postgresData' # volume para a base de dados
      - './postgres:/docker-entrypoint-initdb.d'
  go: # imagem para go
    build:
      context: '.'
      dockerfile: './go/Dockerfile'
    depends_on:
     - 'postgres'
    ports:
      - '8000:8000'
    networks: 
      - 'firstproject'
    volumes:
      - './go/app:/go/src/github.com/app/restapi'
    environment:
      - DEBUG = true
    links:
      - postgres
  angular:
    build:
      context: '.'
      dockerfile: './angular/Dockerfile'
    depends_on:
      - 'postgres'
      - 'go'
    ports:
      - '4200:4200'
    networks: 
      - 'firstproject'
    volumes:
      - './angular/angular-app/:/home/angular/app'
    environment:
      - DEBUG = true
volumes:
  postgresData: {}

networks: # cria network
  firstproject: